name: Release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    name: Build
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1.0.2
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1.0.0

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: go build -ldflags "-s -w" -v cmd/main.go

      - name: Test
        run: go test -v -race ./...

      - name: Release artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.platform }}-bl3-auto-vip
          path: ./main